### ISSUE TITLE
Potential bug with users unable to login

### ISSUE THREAD

**Issue by jsduffy** [startsole/StartSOLE-web-app#121]
I got this message at 2:50 PM EST on August 7:

I am doing a SOLE training in Fremont. I have a couple principals having difficulty logging on...Swanderk@fremontschools.net
Abernathya@fremontschools.ne
Boehlert@fremontschools.net
Lockyerj@fremontschools.net
Can you reset password if you have time? If not I will follow up and get back with them later. No worries.

**Comment by jsduffy** [comment]
passwords reset for users so they should be able to get in OK but report on phone included detail that they were seeing 'account already exists' error message

**Comment by drewrwilson** [comment]
I checked each of these accounts and it doesn't appear like there are duplicates. I wonder if they were trying to use social login in addition to the username/pw login? Is that possible?

**Comment by drewrwilson** [comment]
old, doesn't seem relevant any more. closing
