### ISSUE TITLE
This is a kind of nice login layout

### ISSUE THREAD

**Issue by jsduffy** [startsole/StartSOLE-web-app#127]
Just an idea:

https://themes.materializecss.com/pages/admin-log-in

**Comment by drewrwilson** [comment]
screenshotting in case the linked page is ever down 

![image](https://user-images.githubusercontent.com/4324656/58823539-ed8f5f00-8607-11e9-9593-be7e570df32e.png)

**Comment by drewrwilson** [comment]
we'll leave this for now. might come back as part of a bigger design improvement. let's not do this now tho

**Comment by jsduffy** [comment]
updated, done
