### ISSUE TITLE
Materialize cuts off September

### ISSUE THREAD

**Issue by drewrwilson** [startsole/StartSOLE-web-app#136]
![image](https://user-images.githubusercontent.com/4324656/45831945-9726fe00-bcce-11e8-8d8e-8458132b2bd2.png)

https://www.youtube.com/watch?v=kI6MWZrl8v8

**Comment by jsduffy** [comment]
It actually seems to cut off all months that are too long on some displays

**Comment by drewrwilson** [comment]
I filed (an issue with Materialize)[https://github.com/Dogfalo/materialize/issues/6132] last year. Looks like (they fixed it)[https://github.com/Dogfalo/materialize/issues/6002] in the latest version of Materialize (it's only a small update). We're using v1.0.0-rc1 they are now on v1.0.0 real release. I'm going to test our app locally with the new version. If it appears to work alright, I'll update our `materialize.min.css` file with the new version

**Comment by drewrwilson** [comment]
I've updated from `v1.0.0-rc1` to `v1.0.0` and the end of the month is still being cut off for September and other months. I added an update to Materialize's issues on github. In other news, it appears like the change from `v1.0.0-rc1` to `v1.0.0` is doing fine in the web app, so I'm going to commit those changes

![image](https://user-images.githubusercontent.com/4324656/53517695-1b528e00-3a84-11e9-8f68-10917a3e5600.png)

**Comment by drewrwilson** [comment]
Got it fixed using the solution from here: https://github.com/Dogfalo/materialize/issues/6002
