### ISSUE TITLE
504 error on saving SOLE lesson plans

### ISSUE THREAD

**Issue by jsduffy** [startsole/StartSOLE-web-app#144]
Users are reporting 504 Gateway errors when saving SOLE plans through the site.
from mpleydell@nwoca.org:
"I say mostly successful since we had some issues with a Gateway Timeout Error 

when trying to save a new lesson plan on the website it would try and save but never was successful. We ended up going into the App and creating it in there and facilitated the lesson, connected to the projector and got it to mostly work. The app froze at one point and I had to restart the app and re-connect to the projector.

I am guessing there were some network issues today so it may be an isolated issue. Just wanted to let you know our experience.

I am trying now and was able to get the SOLEs created and saved."

**Comment by drewrwilson** [comment]
this is the everything-error. it means something went wrong somewhere. I think we should close this
