### ISSUE TITLE
Ability to add a standard to questions when creating a new lesson plan

### ISSUE THREAD

**Issue by jsduffy** [startsole/StartSOLE-web-app#154]
When creating a new lesson plan and typing in a question users should be able to select a standard which will be connected to that question and the SOLE.

**Comment by jsduffy** [comment]
Follow up with cbradshaw@southernohioesc.org

**Comment by FransGH** [comment]
There is a new property session.standards containing an array of standards selected for the SOLE. The nightly "fix_question_tags" script will use this information to automatically tag questions.

The Web, iOS and Android client do not need to tag the question. The UI should only offer a way to select standards during lesson planning and reflection (both session.standards).
