### ISSUE TITLE
Comment out the export to spreadsheet from the nightly script

### ISSUE THREAD

**Issue by drewrwilson** [startsole/StartSOLE-web-app#183]
leave it commented out for a couple weeks then go back and remove code for the export

**Comment by jsduffy** [comment]
This is in progress, calendar reminder created

**Comment by drewrwilson** [comment]
Frans commented this out so it's not exporting to a google sheet any more via the nightly script, which is great. Would be good to remove the functions and files from the backend code. @FransGH or @SteffenJ would you want to take on the next part of this?
