### ISSUE TITLE
When approving a SOLE, include an option to trigger a request for permission to share on social media

### ISSUE THREAD

**Issue by jsduffy** [startsole/StartSOLE-web-app#192]
When approving a SOLE, it would be helpful to be able to automatically trigger a request for sharing on social media.  This could be as simple as a checkbox on the approval screen or some other boolean option.  It should

- only be available to admin team people (i.e. if ambassadors are triggering approval they should not be able to request social media permission)
- when checked/marked as true it should send out an email to the user who created the SOLE using the permission template (Justin has this)
- the reply to address for that email should be support@startsole.org
- the email should either include a link to a Google drive folder for reviewing photos (current implementation) or link/attachment of summary document.

**Comment by drewrwilson** [comment]
deployed
