### ISSUE TITLE
Add option to share completed SOLEs on social media

### ISSUE THREAD

**Issue by jsduffy** [startsole/StartSOLE-web-app#201]
Add an option for users to share completed (and approved) SOLEs on social media.  

Eample sharing: https://www.gettingsmart.com/2017/04/sole-hacking-todays-education-for-the-future/

**Comment by drewrwilson** [comment]
frontend code is in the branch called `feature-social-media-request-email-for-realz-tho` I need some help finishing up the backend part of this before we can deploy it. here's the related issue on the backend project: https://github.com/startsole/StartSOLE-backend/issues/66

**Comment by drewrwilson** [comment]
deployed
