### ISSUE TITLE
Add 1 page infographic on SOLE to resources section

### ISSUE THREAD

**Issue by jsduffy** [startsole/StartSOLE-web-app#208]
This could also be linked to the How To section.  Adopt the 1 page infographic from here: https://www.gettingsmart.com/2017/04/sole-hacking-todays-education-for-the-future/

**Comment by drewrwilson** [comment]
![image](https://user-images.githubusercontent.com/4324656/53122125-d8446800-3523-11e9-8ffe-b78e809ada18.png)

**Comment by drewrwilson** [comment]
added a pdf version of this

**Comment by drewrwilson** [comment]
commited to master. didn't deploy yet. can go out on next deploy
