### ISSUE TITLE
A tool to support local SOLE rings

### ISSUE THREAD

**Issue by jsduffy** [startsole/StartSOLE-web-app#216]
Ideally we want a simple tool (iFrame/Word Press plugin/whatever) that allows new SOLE sites to use our question database and register users with our network. The admins should also be able to export users who have signed up via their site (i.e. if I am the admin for SOLE NY I can export a list of all the users who signed up using my instance of the tool).

This could be similar to what we've done with HRSA/are exploring with Colombia

**Comment by drewrwilson** [comment]
closing because it's too broad. starting a new one for integrating spanish for colombia ring
