### ISSUE TITLE
Add a system for continuous deployment - when you push to master, it deploys

### ISSUE THREAD

**Issue by drewrwilson** [startsole/StartSOLE-web-app#231]
Add some continuous deployment / continuous integration stuff that will automatically deploy the code to staging or master when you push code to `master`. eg Jekins or Travis CI

ideally: have a branch called `staging` that automatically deploys to the staging server when it gets pushed to and when we push to `master` it gets deployed to production. 

ideally plus plus: run some tests on push to ensure that everything works and whatnot before deploying

**Comment by jsduffy** [comment]
This is great. Also would be how to do things like tinify images etc

**Comment by drewrwilson** [comment]
update: working on getting circle ci set up. it's free for one project, has more free options for open source projects, might have a nonprofit account (I contacted them about a nonprofit account they said to first try the free tier and contact them if we need more stuff)

there's a pretty good video from fun fun function about it. I'm using it to learn about it and set it up: https://www.youtube.com/watch?v=7VxBn_ZgOek (thanks @SteffenJ for introducing me to fun fun function)

**Comment by drewrwilson** [comment]
daaaaaang, we got an automated deploy process for this! it's far from perfect but now when you push to `master` circle ci will automatically deploy to the production server. and when we push to `staging` circle ci will now automatically deploy to the staging server. 

next steps: 
set up a process where we only make feature branches then we merge them into `staging` then we merge them into `master`
