### ISSUE TITLE
Sign In with Google is hanging for some users

### ISSUE THREAD

**Issue by jsduffy** [startsole/StartSOLE-web-app#238]
We received a report from Derrick Lyons (UserPub:XL2938Zykr) that he was able to login on iOS and Android devices but was hanging on a laptop at this screen:

![image](https://user-images.githubusercontent.com/7926758/54041857-c9ea8300-4196-11e9-85e5-4db901e7be6c.png)

We've reached out to schedule a hangout and observe the issue if possible, otherwise recommended clearing browser cache.  However, we should email derrick.lyons@wchcs.org when this is resolved.

**Comment by drewrwilson** [comment]
related to #350

**Comment by drewrwilson** [comment]
we think this is fixed now with the deploy we just did. we also added logging to send a message on slack if a google user fails logging in again. we'll need to come back and check in a few days or a few weeks
