### ISSUE TITLE
Setup 505 page for graceful maintenance mode

### ISSUE THREAD

**Issue by jsduffy** [startsole/StartSOLE-web-app#278]
This is just a static page that needs to get configured on nginx

**Comment by jsduffy** [comment]
also... this is actually about  a504 error... right?

**Comment by jsduffy** [comment]
Here is a tutorial on how to do this:
https://www.digitalocean.com/community/tutorials/how-to-configure-nginx-to-use-custom-error-pages-on-ubuntu-14-04

We can use the fail page already created, just customize the message if necessary and maybe include an alternate way for people to let us know something is up (Google form/whatever).

**Comment by jsduffy** [comment]
Also this:
https://support.cloudflare.com/hc/en-us/articles/200172706-How-do-I-customize-Cloudflare-error-pages-

**Comment by drewrwilson** [comment]
we'd need a static file in the backend and nginx points to it when we want it enabled

**Comment by drewrwilson** [comment]
closing this issue here, added an issue to the backend for frans:
