### ISSUE TITLE
Geofence localized content

### ISSUE THREAD

**Issue by jsduffy** [startsole/StartSOLE-web-app#308]
We want out site to be available in languages only within rings we designate.  We need to provide a single fixed URL for people to enter from this ring or for this language.

**Comment by jsduffy** [comment]
once this is up on staging we can test #310

**Comment by drewrwilson** [comment]
test these scenarios:
 * a user registers on /register-colombia and gets the app entirely in spanish and is added to the colombia
 * a existing non-colombia user logins into /login-colombia and the login page is in spanish but everything after is in english
 * a existing colombia user logins into /login-colombia and everything is in spanish
 * a existing colombia user logins to the regular login /login and everything after the login page is in spanish

**Comment by jsduffy** [comment]
afaik @drewrwilson closed this one.  it's in the wild now.
