### ISSUE TITLE
209 error (invalid session tokens)

### ISSUE THREAD

**Issue by jsduffy** [startsole/StartSOLE-web-app#320]
We're picking up 209 errors on the backend_bot channel that seem to be related to calls from the webapp which are missing session tokens.

![image](https://user-images.githubusercontent.com/7926758/57943472-20182880-78a2-11e9-880f-6966dc280bc8.png)

Make sure calls like this in Webapp.js have session.useToken
![image](https://user-images.githubusercontent.com/7926758/57943581-62416a00-78a2-11e9-96ce-29c06585fd3f.png)

**Comment by SteffenJ** [comment]
The session tokens are not undefined but their value is the string "undefined".

**Comment by jsduffy** [comment]
Good man @SteffenJ.

**Comment by drewrwilson** [comment]
pushed an update for this. working locally. have a weird error on staging where it's failing on the logger. going to move on to another issue in the meantime so we can talk about it tomorrow during the meeting. i'm stumped

**Comment by drewrwilson** [comment]
turns out this is a parse version thing. steffen and I added code in the webapp client to account for the different ways that parse handles this depending on version
