### ISSUE TITLE
make a UI for a user to manage their email notification preferences

### ISSUE THREAD

**Issue by drewrwilson** [startsole/StartSOLE-web-app#360]
add UI in the `/profile` view where a user can manage their preferences about which kinds of emails to receive

**Comment by jsduffy** [comment]
[Here's a tutorial for the API](https://docs.google.com/document/d/1yQPePagg0jfIrgew8274QP8-_Jn6Dt_gpRbRIhtxvZY/edit)

**Comment by drewrwilson** [comment]
Based on the document above, it seems like we're not deciding a specific set of types of notifications to put into the view but instead pulling it from the database. Leaving this as note for myself when I come back to this

**Comment by drewrwilson** [comment]
preview of the UI:

![image](https://user-images.githubusercontent.com/4324656/59202670-f7b2df80-8b6a-11e9-9bf1-fd6ee722cd8c.png)

**Comment by drewrwilson** [comment]
Note: Since this text is going to need to be translated into Spanish too, when I make the commit I want the English text to be confirmed. I'll finish this all up and before we merge it into `staging`, let's quickly review the text to confirm it. I took my best guess at it but good to double check.

Here are the texts that I need:
 * [ ] Header, currently: "Email Preferences"
 * [ ] Label for "New CEUs Awarded"
 * [ ] Label for "Question Tips"
 * [ ] Label for "Lesson Plan Documents"
 * [ ] Label for "Lesson Summary Documents"
 * [ ] Label for "Reflection Reminders"

**Comment by drewrwilson** [comment]
Another Note: 
If I were a user, I would expect that this is a place where I could indicate my preferences about receiving marketing emails like the mailchimp sequence emails or misc updates about the app. But I didn't find that in mailer flag documentation. Just want to check is that a decision or just overlooked? Just want to know if I should be adding it or not.
