### ISSUE TITLE
Change /dashboard?ring=xxxxx to /rings/:id

### ISSUE THREAD

**Issue by jsduffy** [startsole/StartSOLE-web-app#407]
not this
https://app.startsole.org/dashboard?ring=CXCYoKu8vy

**Comment by drewrwilson** [comment]
notes for myself:

* [ ] `/rings/:id/`  - current view
* [ ] `/rings/:id/educators` - one for each graph on the overview page, maybe stretch (like `/profile/...`
* [ ] `/rings/:id/members` - maybe
* [ ] /rings/:id/schools` - maybe

**Comment by drewrwilson** [comment]
deployed to staging! closing
