### ISSUE TITLE
Create list of ringleaders with associated ring

### ISSUE THREAD

**Issue by SteffenJ** [startsole/StartSOLE-web-app#426]
Create a list of ringleader with the rings where they are a leader from.
We will use this to add their user ids to the ACL lists.

We also need a list of super ring leaders. They will be added to the super_ringleader role which has access to all rings.

**Comment by jsduffy** [comment]
@FransGH is going to follow up with Jeff re: strategic decisions about this.  [Here](https://www.education.pa.gov/Educators/ContinuinEd/Act%2048%20and%20PERMS/Pages/default.aspx) is the website @jsduffy mentioned with more information about Act 48 for context.

**Comment by jsduffy** [comment]
[Here is a spreadsheet](https://docs.google.com/spreadsheets/d/1tm5YZJJ8kwbrwsItogpWRWUF50XvBoMkJfRlRCsjAT4/edit#gid=0) with a list of current ringleaders and associated rings.  As we do PA we will update this spreadsheet and the ACLs.
