### ISSUE TITLE
Confirm RDN names for rings

### ISSUE THREAD

**Issue by drewrwilson** [startsole/StartSOLE-web-app#436]
In the backend we have a file defining the rings, called `polygons.js`. Steffen and I made some RDNs for each one but we just guessed these are just strings and can be anything as long as they are unique. We will use them internally to reference rings but also the user will see it in the URL when they're viewing the ring, something like, `/rings/us.colombiana/`. 

Justin, after we commit this file could you look through it and make sure the rdns are ok? You can change them to whatever as long as they're unique.

**Comment by jsduffy** [comment]
this now seems redundant... already on production.  closing
